# Autogenerated wrapper script for tree_sitter_r_jll for aarch64-apple-darwin
export libtreesitter_r

JLLWrappers.@generate_wrapper_header("tree_sitter_r")
JLLWrappers.@declare_library_product(libtreesitter_r, "@rpath/libtreesitter_r.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libtreesitter_r,
        "lib/libtreesitter_r.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
