# Autogenerated wrapper script for tree_sitter_r_jll for i686-linux-gnu
export libtreesitter_r

JLLWrappers.@generate_wrapper_header("tree_sitter_r")
JLLWrappers.@declare_library_product(libtreesitter_r, "libtreesitter_r.so")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libtreesitter_r,
        "lib/libtreesitter_r.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
